/* This file includes the autogenerated configuration headers
 * please do not edit the included files, edit the .conf
 * files instead and run make to rebuild the headers
 */


#ifndef _RES_PR_CONF_H_
#define _RES_PR_CONF_H_

/* parts */
#include "res_conf_parts.h"
/* files */
#include "res_conf_files.h"
/* types */
#include "res_conf_types.h"
/* mods */
#include "res_conf_mods.h"
/* resources */
#include "res_conf_resources.h"

#endif

