/* This file includes the autogenerated configuration headers
 * please do not edit the included files, edit the .conf
 * files instead and run make to rebuild the headers
 */


#ifndef _STATES_PR_CONF_H_
#define _STATES_PR_CONF_H_

/* animation frame flag options */
#include "states_conf_flags.h"
/* condition properties */
/*#include "states_conf_properties.h" DEPRECATED */
/* state/action, animation and condition lists */
#include "states_conf_static.h"

#endif

