#define TILE_EMPTY 0x00            /*  0 free      */
#define TILE_FLOOR 0x01            /*  1 free      */
#define TILE_SPIKES 0x02           /*  2 spike     */
#define TILE_PILLAR 0x03           /*  3 none      */
#define TILE_GATE 0x04             /*  4 gate      */
#define TILE_BTN_STUCK 0x05        /*  5 none      */
#define TILE_BTN_DROP 0x06         /*  6 event     */
#define TILE_TAPESTRY 0x07         /*  7 tapest    */
#define TILE_BP_BOTTOM 0x08        /*  8 none      */
#define TILE_BP_TOP 0x09           /*  9 none      */
#define TILE_POTION 0x0a           /* 10 potion    */
#define TILE_LOOSE 0x0b            /* 11 none      */
#define TILE_TAPESTRY_TOP 0x0c     /* 12 ttop      */
#define TILE_MIRROR 0x0d           /* 13 none      */
#define TILE_DEBRIS 0x0e           /* 14 none      */
#define TILE_BTN_RAISE 0x0f        /* 15 event     */
#define TILE_EXIT_LEFT 0x10        /* 16 none      */
#define TILE_EXIT_RIGHT 0x11       /* 17 none      */
#define TILE_CHOPPER 0x12          /* 18 chomp     */
#define TILE_TORCH 0x13            /* 19 none      */
#define TILE_WALL 0x14             /* 20 wall      */
#define TILE_SKELETON 0x15         /* 21 none      */
#define TILE_SWORD 0x16            /* 22 none      */
#define TILE_BALCONY_LEFT 0x17     /* 23 none      */
#define TILE_BALCONY_RIGHT 0x18    /* 24 none      */
#define TILE_LATTICE_PILLAR 0x19   /* 25 none      */
#define TILE_LATTICE_SUPPORT 0x1a  /* 26 none      */
#define TILE_LATTICE_SMALL 0x1b    /* 27 none      */
#define TILE_LATTICE_LEFT 0x1c     /* 28 none      */
#define TILE_LATTICE_RIGHT 0x1d    /* 29 none      */
#define TILE_TORCH_DEBRIS 0x1e     /* 30 none      */
#define TILE_NULL 0x1f             /* 31 none      */
