/* This file includes the autogenerated configuration headers
 * please do not edit the included files, edit the .conf
 * files instead and run make to rebuild the headers
 */


#ifndef _TILES_PR_CONF_H_
#define _TILES_PR_CONF_H_

/* tile types */
#include "tiles_conf_types.h"
/* tile groups */
#include "tiles_conf_groups.h"

#endif

